### ISSUE TITLE
Brew warning on "bottle :unneeded"

### ISSUE THREAD

**Issue by cakuki** [coretech/homebrew-terrafile#1]
All brew commands that read terrafile formula from this tap generates the following warning:

```
sh
$> brew search terrafile
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the coretech/terrafile tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/coretech/homebrew-terrafile/Formula/terrafile.rb:6
```

I saw that `GoReleaser` is being used in this repository, and this issue has been resolved there already: https://github.com/goreleaser/goreleaser/pull/2591

Would you be able to update GoReleaser and regenerate tap files? I am also going to open a PR to just fix the tap, so you can choose one of these two options.

**Comment by nritholtz** [comment]
We just released a new version that should fix this issue, can you please try again?
